development:
  secret_key_base: 836bd0792452284e58be8d3e7dccbec137249ad7bb1b224064dc4034f164450d59859a337dd59f6ea67e4ae60e4e42aec9c28b02615cb05ffed1dedaf25b6f0b

test:
  secret_key_base: 836bd0792452284e58be8d3e7dccbec137249ad7bb1b224064dc4034f164450d59859a337dd59f6ea67e4ae60e4e42aec9c28b02615cb05ffed1dedaf25b6f0b

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

